image: python:3.6-slim

before_script:
    - python -V # Print out python version for debugging

test_job:
    stage: test
    script:
        - echo "Running tests"
        - python -m unittest discover -s "./tests/"

pages:
    stage: deploy
    script:
    - echo 'Nothing to do...'
    artifacts:
      paths:
      - public
    only:
    - doc
