#!/usr/bin/python

from ryser.examples import eg6, fail6
from ryser.hall import symmetric_hall_inequality_on_cells, \
                       symmetric_hall_numbers, hall_subgraphs

S = fail6[0]

hall_nums = symmetric_hall_numbers(eg6, S)

print "Subgraph: " + str(S)
print "Hall numbers: "  + str(hall_nums)
print "Sum of Hall numbers: " + str(sum(hall_nums))
print "No of vertices: " + str(len(S))

#hall_subgraphs(eg6, S, with_labels = True, format = 'png')

assert not symmetric_hall_inequality_on_cells(eg6, S)

