#!/usr/bin/python

from ryser.examples import eg4, fail4

from ryser.hall import hall_inequality_on_cells, \
                           symmetric_hall_inequality_on_cells

bad_set = fail4[0]

assert hall_inequality_on_cells(eg4, bad_set)
assert not symmetric_hall_inequality_on_cells(eg4, bad_set)

from ryser.hall import symmetric_hall_numbers, hall_subgraphs

hall_nums = symmetric_hall_numbers(eg4, bad_set)

print "Hall numbers: "  + str(hall_nums)
print "Sum of Hall numbers: " + str(sum(hall_nums))
print "No of vertices: " + str(len(bad_set))

hall_subgraphs(eg4, bad_set)

