#!/usr/bin/python

# 1 2 3 5 . . . .   1  2  3  4  5  6  7  8
# 2 1 3 6 . . . .   9 10 11 12 13 14 15 16
# 3 1 4 2 . . . .  17 18 19 20 21 22 23 24
# 5 6 2 1 . . . .  25 26 27 28 29 30 31 32
# . . . . . 1 . .  33 34 35 36 37 38 39 40
# . . . . 1 . . .  41 42 43 44 45 46 47 48
# . . . . . . . 2  49 50 51 52 53 54 55 56
# . . . . . . 2 .  57 58 59 60 61 62 63 64

size = 8

P = { 1:1,  2:2,  3:3,  4:5, \
      9:2, 10:1, 11:3, 12:6, \
     17:3, 18:1, 19:4, 20:2, \
     25:5, 26:6, 27:2, 28:1, \
     38:1, 
     45:1, \
     56:2, \
     63:2 }

bad_set = [ 5, 6, 7, 8,\
           13,14,15,16,\
           21,22,23,24,\
           29,30,31,32,\
                 39,40,\
                 47,48]

from ryser.hall import hall_inequality_on_cells, \
                           symmetric_hall_inequality_on_cells

assert hall_inequality_on_cells(P, size, bad_set)
assert not symmetric_hall_inequality_on_cells(P, size, bad_set)

from ryser.hall import symmetric_hall_numbers, hall_subgraphs

hall_nums = symmetric_hall_numbers(P, size, bad_set)

print "Hall numbers: "  + str(hall_nums)
print "Sum of Hall numbers: " + str(sum(hall_nums))
print "No of vertices: " + str(len(bad_set))

hall_subgraphs(P, size, bad_set)

