#!/usr/bin/python

# Testing Hilton's claim on p.5 of:
#   "CPLS: Cropper's Question" by Bobga, Goldwasser, Hilton and Johnson.
#

# . . 7 3 5 . . 
# . . . . 6 1 5 
# . 6 . . . . 3
# 6 . . . . . .
# 4 . . . . . . 
# 2 . 1 . . . . 
# 3 4 2 . . . . 

import ryser
import sys

from ryser.examples import eg1, fail1
from ryser.hall import hall_inequality_on_cells

def f(n, k):
    if k >= len(bin(n)) - 2:
        return True
    else:
        return bool(int(bin(n)[2:][::-1][k]))

A = fail1[0]
n = int(sys.argv[1])
m = int(sys.argv[2])

for k in range(n, m + 1):

    X = (a for a in A if f(k, A.index(a)))
    if not hall_inequality_on_cells(eg1, X):
        print k, [a for a in A if f(k, A.index(a))]

